"""The music player's listing: songplay disassembled from its hunks into re/songplay.lst.

songplay is a hunk executable of its own, which the game loads with LoadSeg (re/notes/music.md).
The listing lays it out at addresses of its own - CODE from 0x0000, DATA from 0x1000, BSS
from 0x2000 - so that a CODE address is the offset the port's comments give as
`orig songplay+0x....`.  Every relocated long is shown with the name of what it points at; the
names are the file's own symbols and those of re/songplay_names.txt.  DATA follows as words
and longs by name, the note table and the durations as tables.

    .venv/bin/python tools/disasm_player.py        writes re/songplay.lst (about a second)

re/songplay.lst is versioned, like re/Wings.lst, and held to this regeneration by
tests/test_generated.py: run this after changing re/songplay_names.txt and commit the result.
"""
import argparse
import os
import struct
import sys

from capstone import Cs, CS_ARCH_M68K, CS_MODE_M68K_000

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import hunk                                                     # noqa: E402

PLAYER = os.path.join(ROOT, 'original', 'disk', 'Wings_of_Fury', 'songplay')
NAMES = os.path.join(ROOT, 're', 'songplay_names.txt')
OUT = os.path.join(ROOT, 're', 'songplay.lst')
BASES = [0x0000, 0x1000, 0x2000]


def load_names(path=NAMES):
    """{address: (name, comment)} of the names file."""
    out = {}
    with open(path) as handle:
        for line in handle:
            text = line.split('#', 1)[0] if line.lstrip().startswith('#') else line
            if not text.strip():
                continue
            head, _, comment = text.partition(';')
            parts = head.split()
            if len(parts) >= 2:
                out[int(parts[0], 16)] = (parts[1], comment.strip())
    return out


def names_of(segs, extra):
    """Every address's name: the hunks' symbols, then the names file over them."""
    names = {}
    for seg in segs:
        for name, offset in seg.get('symbols', ()):
            if not name.startswith('__H'):
                names[seg['base'] + offset] = name
    names.update({a: n for a, (n, _) in extra.items()})
    return names


def label(address, names):
    """A name for an address: its own, or the nearest name below it with the offset."""
    if address in names:
        return names[address]
    below = [a for a in names if a <= address and address - a < 0x200]
    if not below:
        return '%04x' % address
    base = max(below)
    return '%s+%x' % (names[base], address - base)


def listing():
    segs = hunk.load(PLAYER, bases=BASES)
    extra = load_names()
    names = names_of(segs, extra)
    code = segs[0]
    data = bytes(code['data'])
    relocs = {o for _, offs in code['relocs'] for o in offs}
    md = Cs(CS_ARCH_M68K, CS_MODE_M68K_000)
    lines = ['; songplay, the music player of Wings of Fury: CODE %d bytes with %d relocations, '
             'DATA %d, BSS %d (re/notes/music.md)' % (len(data), len(relocs), len(segs[1]['data']),
                                                       len(segs[2]['data'])),
             '; CODE at 0x0000, DATA at 0x1000, BSS at 0x2000; generated by tools/disasm_player.py', '']
    address = 0
    while address < len(data):
        if address in names:
            lines.append('')
            comment = extra.get(address, ('', ''))[1]
            lines.append('; ' + '=' * 96)
            lines.append('; %s%s' % (names[address], ('   ' + comment) if comment else ''))
            lines.append('%s:' % names[address])
        ins = next(md.disasm(data[address:], address), None)
        if ins is None:
            lines.append('%04x  %-20s dc.w       $%s' % (address, data[address:address + 2].hex(),
                                                        data[address:address + 2].hex()))
            address += 2
            continue
        notes = []
        for o in range(address, address + ins.size):
            if o in relocs:
                notes.append(label(struct.unpack('>L', data[o:o + 4])[0], names))
        if ins.mnemonic in ('bsr.b', 'bsr.w', 'jsr', 'bra.b', 'bra.w', 'beq.b', 'beq.w', 'bne.b',
                            'bne.w') and ins.op_str.startswith('$'):
            target = int(ins.op_str.split('(')[0][1:], 16)
            if target in names:
                notes.append(names[target])
        lines.append('%04x  %-20s %-10s %-34s%s' % (
            address, data[address:address + ins.size].hex(), ins.mnemonic, ins.op_str,
            ('; ' + ', '.join(notes)) if notes else ''))
        address += ins.size

    body = bytes(segs[1]['data'])
    lines += ['', '; ' + '=' * 96, '; DATA', '']
    offset = 0
    ordered = sorted(a for a in names if 0x1000 <= a < 0x1000 + len(body))
    for i, start in enumerate(ordered):
        end = ordered[i + 1] if i + 1 < len(ordered) else 0x1000 + len(body)
        chunk = body[start - 0x1000:end - 0x1000]
        comment = extra.get(start, ('', ''))[1]
        lines.append('%04x  %-22s %d bytes%s' % (start, names[start], len(chunk),
                                                ('   ; ' + comment) if comment else ''))
        for k in range(0, len(chunk), 16):
            lines.append('      %04x  %s' % (start + k, chunk[k:k + 16].hex()))
        offset = end
    return '\n'.join(lines) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description='Regenerate the music player\'s listing.')
    parser.add_argument('--out', default=os.path.dirname(OUT),
                        help='the directory for songplay.lst (default re/)')
    args = parser.parse_args(argv)
    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, os.path.basename(OUT))
    with open(path, 'w') as handle:
        handle.write(listing())
    print('%s written' % (os.path.relpath(path, ROOT) if args.out == os.path.dirname(OUT) else path))


if __name__ == '__main__':
    main()
